package gpay2;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author tiunidaputri
 */
public class homeadm extends javax.swing.JFrame {

    Topup a;
    Account b;
    Mriwayat c;
    Saldo d;

    /**
     * Creates new form homeadm
     */
    public homeadm() {
        initComponents();
        a = new Topup();
        b = new Account();
        c = new Mriwayat();
        d = new Saldo();
        tabAccount.add(a);
        tabAccount.add(b);
        tabAccount.add(c);
        tabAccount.add(d);
        a.setVisible(false);
        b.setVisible(false);
        c.setVisible(false);
        d.setVisible(false);
        menu.setVisible(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabAccount = new javax.swing.JPanel();
        menu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btntopup = new javax.swing.JButton();
        btnaccount = new javax.swing.JButton();
        btnriwayat = new javax.swing.JButton();
        btnsaldo = new javax.swing.JButton();
        btnlogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabAccount.setBackground(new java.awt.Color(255, 255, 204));
        tabAccount.setLayout(new javax.swing.BoxLayout(tabAccount, javax.swing.BoxLayout.LINE_AXIS));

        menu.setBackground(new java.awt.Color(255, 204, 204));

        jLabel1.setText("WELCOME");

        javax.swing.GroupLayout menuLayout = new javax.swing.GroupLayout(menu);
        menu.setLayout(menuLayout);
        menuLayout.setHorizontalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addGap(309, 309, 309)
                .addComponent(jLabel1)
                .addContainerGap(329, Short.MAX_VALUE))
        );
        menuLayout.setVerticalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addGap(172, 172, 172)
                .addComponent(jLabel1)
                .addContainerGap(252, Short.MAX_VALUE))
        );

        tabAccount.add(menu);

        jPanel3.setBackground(new java.awt.Color(255, 153, 153));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
        });
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btntopup.setText("TOP UP");
        btntopup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btntopupMouseClicked(evt);
            }
        });
        btntopup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntopupActionPerformed(evt);
            }
        });
        jPanel3.add(btntopup, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, -1, -1));

        btnaccount.setText("ACCOUNT");
        btnaccount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnaccountMouseClicked(evt);
            }
        });
        jPanel3.add(btnaccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, -1));

        btnriwayat.setText("RIWAYAT TRANSAKSI");
        btnriwayat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnriwayatMouseClicked(evt);
            }
        });
        btnriwayat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnriwayatActionPerformed(evt);
            }
        });
        jPanel3.add(btnriwayat, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, -1, -1));

        btnsaldo.setText("SALDO");
        btnsaldo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnsaldoMouseClicked(evt);
            }
        });
        jPanel3.add(btnsaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, -1, -1));

        btnlogout.setText("LOG OUT");
        btnlogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnlogoutMouseClicked(evt);
            }
        });
        btnlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogoutActionPerformed(evt);
            }
        });
        jPanel3.add(btnlogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tabAccount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabAccount, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btntopupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntopupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btntopupActionPerformed

    private void btntopupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btntopupMouseClicked
        // TODO add your handling code here:
        a.setVisible(true);
        b.setVisible(false);
        c.setVisible(false);
        d.setVisible(false);
        menu.setVisible(false);
    }//GEN-LAST:event_btntopupMouseClicked

    private void btnlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnlogoutActionPerformed

    private void btnriwayatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnriwayatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnriwayatActionPerformed

    private void btnaccountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnaccountMouseClicked
        // TODO add your handling code here:
        b.setVisible(true);
        a.setVisible(false);
        c.setVisible(false);
        d.setVisible(false);
        menu.setVisible(false);

    }//GEN-LAST:event_btnaccountMouseClicked

    private void btnlogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnlogoutMouseClicked
        // TODO add your handling code here:
        login1 login = new login1();
        login.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_btnlogoutMouseClicked

    private void btnriwayatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnriwayatMouseClicked
        // TODO add your handling code here:
        c.setVisible(true);
        a.setVisible(false);
        b.setVisible(false);
        d.setVisible(false);
        menu.setVisible(false);

    }//GEN-LAST:event_btnriwayatMouseClicked

    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseClicked
        // TODO add your handling code here:
        menu.setVisible(true);
        a.setVisible(false);
        b.setVisible(false);
        c.setVisible(false);
        d.setVisible(false);
    }//GEN-LAST:event_jPanel3MouseClicked

    private void btnsaldoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsaldoMouseClicked
        // TODO add your handling code here:
        d.setVisible(true);
        c.setVisible(false);
        a.setVisible(false);
        b.setVisible(false);
        menu.setVisible(false);
    }//GEN-LAST:event_btnsaldoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(homeadm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(homeadm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(homeadm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(homeadm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new homeadm().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnaccount;
    private javax.swing.JButton btnlogout;
    private javax.swing.JButton btnriwayat;
    private javax.swing.JButton btnsaldo;
    private javax.swing.JButton btntopup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel menu;
    private javax.swing.JPanel tabAccount;
    // End of variables declaration//GEN-END:variables
}
