package gpay2;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Lenovo
 */
public class homesec extends javax.swing.JFrame {

    login1 login = new login1();

    /**
     * Creates new form homesec
     */
    public homesec() {
        initComponents();
        login.pack();
        String user = login.txtuser.getText();

        labeluser.setText(user);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnbeli = new javax.swing.JButton();
        btnrp = new javax.swing.JButton();
        btnlg = new javax.swing.JButton();
        labeluser = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnbeli.setText("PEMBELIAN");
        btnbeli.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnbeliMouseClicked(evt);
            }
        });
        btnbeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbeliActionPerformed(evt);
            }
        });

        btnrp.setText("RIWAYAT PEMBELIAN");
        btnrp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnrpMouseClicked(evt);
            }
        });
        btnrp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrpActionPerformed(evt);
            }
        });

        btnlg.setText("LOG OUT");
        btnlg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnlgMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnlgMouseEntered(evt);
            }
        });

        labeluser.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(119, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnbeli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnrp, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE))
                .addGap(129, 129, 129))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(btnlg))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labeluser)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labeluser)
                .addGap(51, 51, 51)
                .addComponent(btnbeli)
                .addGap(18, 18, 18)
                .addComponent(btnrp)
                .addGap(56, 56, 56)
                .addComponent(btnlg)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnrpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnrpActionPerformed

    private void btnbeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbeliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnbeliActionPerformed

    private void btnbeliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbeliMouseClicked
        // TODO add your handling code here:
        S_pembelian beli = new S_pembelian();
        beli.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnbeliMouseClicked

    private void btnrpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnrpMouseClicked
        // TODO add your handling code here:
        Riwayatsec beli = new Riwayatsec();
        beli.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnrpMouseClicked

    private void btnlgMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnlgMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnlgMouseEntered

    private void btnlgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnlgMouseClicked
        // TODO add your handling code here:
        login1 login = new login1();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnlgMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(homesec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(homesec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(homesec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(homesec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new homesec().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbeli;
    private javax.swing.JButton btnlg;
    private javax.swing.JButton btnrp;
    public javax.swing.JLabel labeluser;
    // End of variables declaration//GEN-END:variables
}
