package gpay2;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Lenovo
 */
public class homemhs extends javax.swing.JFrame {

    login1 login = new login1();

    /**
     * Creates new form homemhs
     */
    public homemhs() {
        initComponents();
        login.pack();
        String user = login.txtuser.getText();

        labeluser.setText(user);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnsld = new javax.swing.JButton();
        btnrtp = new javax.swing.JButton();
        btnrp = new javax.swing.JButton();
        btnrt = new javax.swing.JButton();
        btnlg = new javax.swing.JButton();
        labeluser = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnsld.setText("SALDO");
        btnsld.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnsldMouseClicked(evt);
            }
        });

        btnrtp.setText("RIWAYAT TOP UP");
        btnrtp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnrtpMouseClicked(evt);
            }
        });

        btnrp.setText("RIWAYAT PEMBELIAN");
        btnrp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnrpMouseClicked(evt);
            }
        });

        btnrt.setText("RIWAYAT TRANSAKSI");
        btnrt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnrtMouseClicked(evt);
            }
        });

        btnlg.setText("LOG OUT");
        btnlg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnlgMouseClicked(evt);
            }
        });

        labeluser.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(138, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnrt)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnrtp, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnsld, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnrp, javax.swing.GroupLayout.Alignment.LEADING))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnlg)
                        .addGap(37, 37, 37)))
                .addGap(123, 123, 123))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labeluser)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labeluser)
                .addGap(22, 22, 22)
                .addComponent(btnsld)
                .addGap(18, 18, 18)
                .addComponent(btnrtp)
                .addGap(18, 18, 18)
                .addComponent(btnrp)
                .addGap(18, 18, 18)
                .addComponent(btnrt)
                .addGap(18, 18, 18)
                .addComponent(btnlg)
                .addContainerGap(66, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsldMouseClicked
        // TODO add your handling code here:
        saldom saldo = new saldom();
        saldo.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_btnsldMouseClicked

    private void btnrtpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnrtpMouseClicked
        // TODO add your handling code here:
        riwayattopupm rtp = new riwayattopupm();
        rtp.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_btnrtpMouseClicked

    private void btnrpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnrpMouseClicked
        // TODO add your handling code here:
        riwayatbelim rbl = new riwayatbelim();
        rbl.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_btnrpMouseClicked

    private void btnrtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnrtMouseClicked
        // TODO add your handling code here:
        riwayattransaksim rtr = new riwayattransaksim();
        rtr.setVisible(true);

        this.dispose();
        
    }//GEN-LAST:event_btnrtMouseClicked

    private void btnlgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnlgMouseClicked
        // TODO add your handling code here:
        login1 login = new login1();
        login.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_btnlgMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(homemhs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(homemhs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(homemhs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(homemhs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new homemhs().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnlg;
    private javax.swing.JButton btnrp;
    private javax.swing.JButton btnrt;
    private javax.swing.JButton btnrtp;
    private javax.swing.JButton btnsld;
    public javax.swing.JLabel labeluser;
    // End of variables declaration//GEN-END:variables
}
