/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gpay2;

/**
 *
 * @author Lenovo
 */
public class Mriwayat extends javax.swing.JPanel {

    Mriwayattopup a;
    Mriwayattransaksi b;
    Mriwayatbeli c;

    /**
     * Creates new form Mriwayat
     */
    public Mriwayat() {
        initComponents();
                a = new Mriwayattopup();
        b = new Mriwayattransaksi();
        c = new Mriwayatbeli();
        tab.add(a);
        tab.add(b);
        tab.add(c);
        a.setVisible(false);
        b.setVisible(false);
        c.setVisible(false);
        menu.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tab = new javax.swing.JPanel();
        menu = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        RP = new javax.swing.JButton();
        RT = new javax.swing.JButton();
        RTP = new javax.swing.JButton();

        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        tab.setBackground(new java.awt.Color(255, 204, 204));
        tab.setLayout(new javax.swing.BoxLayout(tab, javax.swing.BoxLayout.LINE_AXIS));

        menu.setBackground(new java.awt.Color(255, 204, 204));

        javax.swing.GroupLayout menuLayout = new javax.swing.GroupLayout(menu);
        menu.setLayout(menuLayout);
        menuLayout.setHorizontalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 659, Short.MAX_VALUE)
        );
        menuLayout.setVerticalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        tab.add(menu);

        jPanel1.setBackground(new java.awt.Color(255, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        RP.setText("RIWAYAT PEMBELIAN");
        RP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RPMouseClicked(evt);
            }
        });
        jPanel1.add(RP, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 139, -1));

        RT.setText("RIWAYAT TRANSAKSI");
        RT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RTMouseClicked(evt);
            }
        });
        jPanel1.add(RT, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, -1, -1));

        RTP.setText("RIWAYAT TOP UP");
        RTP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RTPMouseClicked(evt);
            }
        });
        RTP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RTPActionPerformed(evt);
            }
        });
        jPanel1.add(RTP, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 139, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 659, Short.MAX_VALUE)
            .addComponent(tab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseClicked

    private void RPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RPMouseClicked
        // TODO add your handling code here:
        c.setVisible(true);
        b.setVisible(false);
        a.setVisible(false);
        menu.setVisible(false);
    }//GEN-LAST:event_RPMouseClicked

    private void RTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RTMouseClicked
        // TODO add your handling code here:
        b.setVisible(true);
        a.setVisible(false);
        c.setVisible(false);
        menu.setVisible(false);
    }//GEN-LAST:event_RTMouseClicked

    private void RTPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RTPMouseClicked
        // TODO add your handling code here:
        a.setVisible(true);
        b.setVisible(false);
        c.setVisible(false);
        menu.setVisible(false);
    }//GEN-LAST:event_RTPMouseClicked

    private void RTPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RTPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RTPActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton RP;
    private javax.swing.JButton RT;
    private javax.swing.JButton RTP;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel menu;
    private javax.swing.JPanel tab;
    // End of variables declaration//GEN-END:variables
}
