/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gpay2;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class S_pembelian extends javax.swing.JFrame {

    private static Connection con;
    private static Statement stat;
    private static ResultSet res;
    homesec home = new homesec();
    public String user = home.labeluser.getText();

    /**
     * Creates new form S_pembelian
     */
    public S_pembelian() {
        initComponents();
        koneksi();
        beli();
        batal.setVisible(false);
        clear.setVisible(false);
    }

    private void koneksi() {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/gpay", "root", "");
            stat = con.createStatement();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "belum terkoneksi :(");
        }
    }

    private void beli() {
        try {
            res = stat.executeQuery("select * from saldo where username = '" + txtusernametp.getText() + "' "
                    + "and password = '" + txtpwtp.getText() + "';");
            if (res.next()) {
                if (txtusernametp.getText().equals(res.getString("username")) && txtpwtp.getText().equals(res.getString("password"))) {
                    String a = txtnomtp.getText();
                    int saldokurang = Integer.parseInt(a);
                    res = stat.executeQuery("select saldo from saldo where username = '" + txtusernametp.getText() + "' "
                            + "and password = '" + txtpwtp.getText() + "';");
                    res.next();
                    String str = res.getString("saldo");
                    int saldoakhir = Integer.parseInt(str);
                    int saldobaru = saldoakhir - saldokurang;

                    res = stat.executeQuery("select nama from account where username = '" + txtusernametp.getText() + "' "
                            + "and password = '" + txtpwtp.getText() + "';");
                    res.next();
                    String namapembeli = res.getString("nama");

                    res = stat.executeQuery("select saldo from saldo where username = '" + user + "';");
                    res.next();
                    String string = res.getString("saldo");
                    int saldoakhirsektor = Integer.parseInt(string);
                    int saldobarusektor = saldoakhirsektor + saldokurang;

                    res = stat.executeQuery("select password from saldo where username = '" + user + "';");
                    res.next();
                    String passwordsektor = res.getString("password");

                    if (saldokurang < saldoakhir) {
                        stat.executeUpdate("update saldo set saldo = '" + saldobaru + "' where username = '" + txtusernametp.getText() + "' "
                                + "and password = '" + txtpwtp.getText() + "';");
                        stat.executeUpdate("update saldo set saldo = '" + saldobarusektor + "' where username = '" + user + "';");

                        stat.executeUpdate("insert into riwayat values ('" + txtusernametp.getText() + "', '"
                                + txtpwtp.getText() + "', '" + saldokurang + "', 'TRANSFER', 'KOPERASI MAHASISWA'), ('" + user + "', '"
                                + passwordsektor + "', '" + saldokurang + "', 'TRANSFER', '" + namapembeli + "');");

                        txtusernametp.setText("");
                        txtpwtp.setText("");
                        txtnomtp.setText("");
                        JOptionPane.showMessageDialog(null, "Pembelian berhasil! :)");
                    } else if (saldokurang > saldoakhir) {
                        try {
                            JOptionPane.showMessageDialog(null, "Sisa Saldo anda = " + saldoakhir + ", mohon top up dulu!", "Saldo Kurang", JOptionPane.WARNING_MESSAGE);
                        } catch (Exception e) {
                        }
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "username atau password salah");
                }
            }

        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        account = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtusernametp = new javax.swing.JTextField();
        txtpwtp = new javax.swing.JPasswordField();
        txtnomtp = new javax.swing.JTextField();
        btntp = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        batal = new javax.swing.JLabel();
        clear = new javax.swing.JButton();
        BACK = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        account.setBackground(new java.awt.Color(255, 204, 204));

        jLabel3.setText("Nominal Pembelian");

        txtusernametp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtusernametpActionPerformed(evt);
            }
        });

        txtpwtp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpwtpActionPerformed(evt);
            }
        });

        txtnomtp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnomtpActionPerformed(evt);
            }
        });

        btntp.setText("Transfer");
        btntp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btntpMouseClicked(evt);
            }
        });
        btntp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntpActionPerformed(evt);
            }
        });

        jLabel1.setText("Username");

        jLabel2.setText("Password");

        batal.setText("Pembelian dibatalkan");

        clear.setText("Clear");
        clear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clearMouseClicked(evt);
            }
        });

        BACK.setText("BACK");
        BACK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BACKMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout accountLayout = new javax.swing.GroupLayout(account);
        account.setLayout(accountLayout);
        accountLayout.setHorizontalGroup(
            accountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accountLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BACK)
                .addGroup(accountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(accountLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel3)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, accountLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(accountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(accountLayout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addGroup(accountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)))
                            .addGroup(accountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtnomtp, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtpwtp, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtusernametp, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(accountLayout.createSequentialGroup()
                                .addComponent(batal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(clear)))
                        .addContainerGap(148, Short.MAX_VALUE))))
            .addGroup(accountLayout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addComponent(btntp)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        accountLayout.setVerticalGroup(
            accountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accountLayout.createSequentialGroup()
                .addGroup(accountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(accountLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel1))
                    .addGroup(accountLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BACK)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtusernametp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtpwtp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtnomtp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(accountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(batal)
                    .addComponent(clear))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btntp)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(account, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(account, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtusernametpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtusernametpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtusernametpActionPerformed

    private void txtpwtpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpwtpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpwtpActionPerformed

    private void txtnomtpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnomtpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnomtpActionPerformed

    private void btntpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btntpMouseClicked
        if (txtusernametp.getText().equals("") && txtpwtp.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Mohon isi dulu");
        } else {
            int input = JOptionPane.showConfirmDialog(null, "Benar ingin melakukan pembelian sebesar " + txtnomtp.getText()
                    + " pada akun " + txtusernametp.getText() + "?", "Transfer", JOptionPane.YES_NO_OPTION);
            if (input == 0) {
                batal.setVisible(false);
                clear.setVisible(false);
                beli();
            } else if (input == 1) {
                batal.setVisible(true);
                clear.setVisible(true);
            }
        }
    }//GEN-LAST:event_btntpMouseClicked

    private void btntpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btntpActionPerformed

    private void clearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearMouseClicked
        // TODO add your handling code here:
        txtusernametp.setText("");
        txtpwtp.setText("");
        txtnomtp.setText("");
        batal.setVisible(false);
        clear.setVisible(false);
    }//GEN-LAST:event_clearMouseClicked

    private void BACKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BACKMouseClicked
        // TODO add your handling code here:
        homesec home = new homesec();
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BACKMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(S_pembelian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(S_pembelian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(S_pembelian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(S_pembelian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new S_pembelian().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BACK;
    private javax.swing.JPanel account;
    private javax.swing.JLabel batal;
    private javax.swing.JButton btntp;
    private javax.swing.JButton clear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtnomtp;
    private javax.swing.JPasswordField txtpwtp;
    private javax.swing.JTextField txtusernametp;
    // End of variables declaration//GEN-END:variables
}
