/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gpay2;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class Topup extends javax.swing.JPanel {

    private static Connection con;
    private static Statement stat;
    private static ResultSet res;

    /**
     * Creates new form Topup
     */
    public Topup() {
        initComponents();
        koneksi();
        topup();
        batal.setVisible(false);
        clear.setVisible(false);
    }

    private void koneksi() {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/gpay", "root", "");
            stat = con.createStatement();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "belum terkoneksi :(");
        }
    }

    private void topup() {
        try {
            res = stat.executeQuery("select * from saldo where username = '" + txtusernametp.getText() + "' "
                    + "and password = '" + txtpwtp.getText() + "';");
            if (res.next()) {
                if (txtusernametp.getText().equals(res.getString("username")) && txtpwtp.getText().equals(res.getString("password"))) {
                    String a = txtnomtp.getText();
                    int saldotambah = Integer.parseInt(a);
                    res = stat.executeQuery("select saldo from saldo where username = '" + txtusernametp.getText() + "' "
                            + "and password = '" + txtpwtp.getText() + "';");
                    res.next();
                    String str = res.getString("saldo");
                    int saldoakhir = Integer.parseInt(str);
                    int saldobaru = saldoakhir + saldotambah;
                    stat.executeUpdate("update saldo set saldo = '" + saldobaru + "' where username = '" + txtusernametp.getText() + "' "
                            + "and password = '" + txtpwtp.getText() + "';");
                    stat.executeUpdate("insert into riwayat values ('" + txtusernametp.getText() + "', '"
                            + txtpwtp.getText() + "', '" + saldotambah + "', 'TOP UP', '');");
                    txtusernametp.setText("");
                    txtpwtp.setText("");
                    txtnomtp.setText("");
                    JOptionPane.showMessageDialog(null, "Top Up berhasil! :)");
                } else {
                    batal.setVisible(true);
                    JOptionPane.showMessageDialog(null, "username atau password salah");
                }
            }

        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        account = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtusernametp = new javax.swing.JTextField();
        txtpwtp = new javax.swing.JPasswordField();
        txtnomtp = new javax.swing.JTextField();
        btntp = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        batal = new javax.swing.JLabel();
        clear = new javax.swing.JButton();

        jPanel3.setLayout(new java.awt.BorderLayout());

        account.setBackground(new java.awt.Color(255, 204, 204));

        jLabel3.setText("Nominal Top Up");

        txtusernametp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtusernametpActionPerformed(evt);
            }
        });

        txtpwtp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpwtpActionPerformed(evt);
            }
        });

        txtnomtp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnomtpActionPerformed(evt);
            }
        });

        btntp.setText("Top Up");
        btntp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btntpMouseClicked(evt);
            }
        });
        btntp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntpActionPerformed(evt);
            }
        });

        jLabel1.setText("Username");

        jLabel2.setText("Password");

        batal.setText("Top Up dibatalkan");

        clear.setText("Clear");
        clear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clearMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout accountLayout = new javax.swing.GroupLayout(account);
        account.setLayout(accountLayout);
        accountLayout.setHorizontalGroup(
            accountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accountLayout.createSequentialGroup()
                .addGap(239, 239, 239)
                .addGroup(accountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, accountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(accountLayout.createSequentialGroup()
                            .addGap(53, 53, 53)
                            .addGroup(accountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2)))
                        .addGroup(accountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtnomtp, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtpwtp, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtusernametp, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(accountLayout.createSequentialGroup()
                            .addComponent(batal)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(clear)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, accountLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(33, 33, 33)))
                .addContainerGap(240, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, accountLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btntp)
                .addGap(282, 282, 282))
        );
        accountLayout.setVerticalGroup(
            accountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accountLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtusernametp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtpwtp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtnomtp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(accountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(batal)
                    .addComponent(clear))
                .addGap(4, 4, 4)
                .addComponent(btntp)
                .addContainerGap(264, Short.MAX_VALUE))
        );

        jPanel3.add(account, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 639, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 639, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 4, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 5, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 639, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 639, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtusernametpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtusernametpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtusernametpActionPerformed

    private void txtpwtpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpwtpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpwtpActionPerformed

    private void txtnomtpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnomtpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnomtpActionPerformed

    private void btntpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btntpMouseClicked
        // TODO add your handling code here:
        int input = JOptionPane.showConfirmDialog(null, "Benar ingin melakukan topup sebesar " + txtnomtp.getText()
                + " pada akun " + txtusernametp.getText() + "?", "top up", JOptionPane.YES_NO_OPTION);
        if (input == 0) {
            batal.setVisible(false);
            clear.setVisible(false);
            topup();
        } else if (input == 1) {
            batal.setVisible(true);
            clear.setVisible(true);
        }

    }//GEN-LAST:event_btntpMouseClicked

    private void btntpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btntpActionPerformed

    private void clearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearMouseClicked
        // TODO add your handling code here:
        txtusernametp.setText("");
        txtpwtp.setText("");
        txtnomtp.setText("");
        batal.setVisible(false);
        clear.setVisible(false);
    }//GEN-LAST:event_clearMouseClicked
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel account;
    private javax.swing.JLabel batal;
    private javax.swing.JButton btntp;
    private javax.swing.JButton clear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txtnomtp;
    private javax.swing.JPasswordField txtpwtp;
    private javax.swing.JTextField txtusernametp;
    // End of variables declaration//GEN-END:variables
}
